### ISSUE TITLE
Error in create/edit field (Block "uploadLocationFields" on template "_components/fieldtypes/elementfieldsettings" does not exist.)

### ISSUE THREAD

**Issue by taher-amici** [alexmarchant/advanced-image-field#4]
we are having this weird issue going on after installing the plugin. when creating a new field we got this error.
![Screenshot from 2019-05-29 16-18-12](https://user-images.githubusercontent.com/51078042/76092219-0d174600-5fe5-11ea-8ce2-e6706d69d37f.png)

**Comment by threepoles** [comment]
+1

**Comment by alexmarchant** [comment]
Ok checking this out

**Comment by alexmarchant** [comment]
Sorry all, I haven't been in the craft world for a bit and too much work to get this going. Happy to refund if craft lets me do that, or happy to take a pull request if you all know whats up.

**Comment by wesleygooch** [comment]
You should pull this plugin from the store if you're not planning to support it anymore. This version isn't compatible with the latest version of Craft. At least notify people in the plugin store of which versions of craft it still works with... would save them their time.

**Comment by alexmarchant** [comment]
I see, didn't realize it was that bad and broken for everyone. I've emailed Pixel and Tonic to request that they disable new downloads of the plugin. Thanks for bringing to my attention.

**Comment by alexmarchant** [comment]
Ok, the plugin has been disabled in the store.

**Comment by alexmarchant** [comment]
I don't have a php dev environment set up right now, but looks like @amos-whitewolf has a PR out for this fix, would anyone else be able to pull and confirm it solves the problem, then I'll merge?

**Comment by proimage** [comment]
I don't know how to try out pull requested modifications to plugins, etc etc, but the change is so simple I recreated it manually on my local dev, and it does fix the issue. I'd go ahead and merge it. ¯\\\_(ツ)_/¯

**Comment by alexmarchant** [comment]
ok done, thanks @proimage @amos-whitewolf
